export const MIN_LOAN_AMOUNT = 2000
export const MAX_LOAN_AMOUNT = 100000
export const MIN_LOAN_DAYS_TIME = 7
export const MAX_LOAN_DAYS_TIME = 30
export const MIN_LOAN_MONTHS_TIME = 2
export const MAX_LOAN_MONTHS_TIME = 12
export const MAX_LOAN_AMOUNT_BY_DAYS = 20000
export const MIN_LOAN_AMOUNT_BY_MONTHS = 21000
export const LOAN_TIME_DAYS_LABEL_TEXT = 'Срок займа'
export const LOAN_TIME_MONTHS_LABEL_TEXT = 'Срок займа в месяцах'
export const LOAN_TIME_DAYS_LABEL_WIDTH = '80px'
export const LOAN_TIME_MONTHS_LABEL_WIDTH = '160px'
export const LITTLE_LOAN_CLASS_NAME = 'little-loan'
export const LARGE_LOAN_CLASS_NAME = 'large-loan'
